name: Secret Scan Test

on: 
  push:
    branches:
      - main

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Simulate a secret
        run: echo "MySecretKey=ghp_1234567890abcdefghijklmnopqrstuvwx"
